---
- hosts: ashu_apps
  tasks:
  - name: running date command 
    command: date
    register: ashu_out  # this variable will be created and store output of date command 
  - name: printing data
    debug: 
     var: ashu_out # printing values 
