---
- hosts: ashu_apps
  tasks:
  - name: install "{{ data }}" in node2 
    yum: 
     name: "{{ data }}"
     state: present
    when: ansible_hostname == "fedora2"

  - name: creating users in node1 only 
    user:
      name: "{{ item }}"
      state: present 
    loop: "{{ users }}"
    when: "'192.168.100.2' in inventory_hostname"  # this inventory_hostname is magic variable which is holding all the IPs in current group
