---
- name: choosing target hosts 
  hosts: ashu_apps
  tasks:
  - name: using ping module to send ICMP request to all the test group targets
    ping: 

  - name: running a command on target linux host
    command: date 

